// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: screenshot_result.proto

package androidx.test.screenshots;

public final class ScreenshotResultProtos {
  private ScreenshotResultProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ScreenshotResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.screenshots.ScreenshotResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.test.screenshots.ScreenshotResult.Status result = 1;</code>
     */
    int getResultValue();
    /**
     * <code>.test.screenshots.ScreenshotResult.Status result = 1;</code>
     */
    androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.Status getResult();

    /**
     * <code>string image_location_test = 2;</code>
     */
    java.lang.String getImageLocationTest();
    /**
     * <code>string image_location_test = 2;</code>
     */
    com.google.protobuf.ByteString
        getImageLocationTestBytes();

    /**
     * <pre>
     *actual location if image exists, expected location if missing
     * </pre>
     *
     * <code>string image_location_golden = 3;</code>
     */
    java.lang.String getImageLocationGolden();
    /**
     * <pre>
     *actual location if image exists, expected location if missing
     * </pre>
     *
     * <code>string image_location_golden = 3;</code>
     */
    com.google.protobuf.ByteString
        getImageLocationGoldenBytes();

    /**
     * <code>string image_location_diff = 4;</code>
     */
    java.lang.String getImageLocationDiff();
    /**
     * <code>string image_location_diff = 4;</code>
     */
    com.google.protobuf.ByteString
        getImageLocationDiffBytes();

    /**
     * <code>.test.screenshots.ScreenshotResult.ComparisonStatistics comparison_statistics = 5;</code>
     */
    boolean hasComparisonStatistics();
    /**
     * <code>.test.screenshots.ScreenshotResult.ComparisonStatistics comparison_statistics = 5;</code>
     */
    androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics getComparisonStatistics();
    /**
     * <code>.test.screenshots.ScreenshotResult.ComparisonStatistics comparison_statistics = 5;</code>
     */
    androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatisticsOrBuilder getComparisonStatisticsOrBuilder();
  }
  /**
   * Protobuf type {@code test.screenshots.ScreenshotResult}
   */
  public  static final class ScreenshotResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.screenshots.ScreenshotResult)
      ScreenshotResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ScreenshotResult.newBuilder() to construct.
    private ScreenshotResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScreenshotResult() {
      result_ = 0;
      imageLocationTest_ = "";
      imageLocationGolden_ = "";
      imageLocationDiff_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ScreenshotResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              result_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              imageLocationTest_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              imageLocationGolden_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              imageLocationDiff_ = s;
              break;
            }
            case 42: {
              androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.Builder subBuilder = null;
              if (comparisonStatistics_ != null) {
                subBuilder = comparisonStatistics_.toBuilder();
              }
              comparisonStatistics_ = input.readMessage(androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(comparisonStatistics_);
                comparisonStatistics_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return androidx.test.screenshots.ScreenshotResultProtos.internal_static_test_screenshots_ScreenshotResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return androidx.test.screenshots.ScreenshotResultProtos.internal_static_test_screenshots_ScreenshotResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.class, androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.Builder.class);
    }

    /**
     * Protobuf enum {@code test.screenshots.ScreenshotResult.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNSPECIFIED = 0;</code>
       */
      UNSPECIFIED(0),
      /**
       * <code>PASSED = 1;</code>
       */
      PASSED(1),
      /**
       * <code>FAILED = 2;</code>
       */
      FAILED(2),
      /**
       * <code>MISSING_GOLDEN = 3;</code>
       */
      MISSING_GOLDEN(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNSPECIFIED = 0;</code>
       */
      public static final int UNSPECIFIED_VALUE = 0;
      /**
       * <code>PASSED = 1;</code>
       */
      public static final int PASSED_VALUE = 1;
      /**
       * <code>FAILED = 2;</code>
       */
      public static final int FAILED_VALUE = 2;
      /**
       * <code>MISSING_GOLDEN = 3;</code>
       */
      public static final int MISSING_GOLDEN_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      public static Status forNumber(int value) {
        switch (value) {
          case 0: return UNSPECIFIED;
          case 1: return PASSED;
          case 2: return FAILED;
          case 3: return MISSING_GOLDEN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:test.screenshots.ScreenshotResult.Status)
    }

    public interface ComparisonStatisticsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:test.screenshots.ScreenshotResult.ComparisonStatistics)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>uint32 number_pixels_identical = 1;</code>
       */
      int getNumberPixelsIdentical();

      /**
       * <code>uint32 number_pixels_different = 2;</code>
       */
      int getNumberPixelsDifferent();
    }
    /**
     * Protobuf type {@code test.screenshots.ScreenshotResult.ComparisonStatistics}
     */
    public  static final class ComparisonStatistics extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:test.screenshots.ScreenshotResult.ComparisonStatistics)
        ComparisonStatisticsOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ComparisonStatistics.newBuilder() to construct.
      private ComparisonStatistics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ComparisonStatistics() {
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ComparisonStatistics(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                numberPixelsIdentical_ = input.readUInt32();
                break;
              }
              case 16: {

                numberPixelsDifferent_ = input.readUInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return androidx.test.screenshots.ScreenshotResultProtos.internal_static_test_screenshots_ScreenshotResult_ComparisonStatistics_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return androidx.test.screenshots.ScreenshotResultProtos.internal_static_test_screenshots_ScreenshotResult_ComparisonStatistics_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.class, androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.Builder.class);
      }

      public static final int NUMBER_PIXELS_IDENTICAL_FIELD_NUMBER = 1;
      private int numberPixelsIdentical_;
      /**
       * <code>uint32 number_pixels_identical = 1;</code>
       */
      public int getNumberPixelsIdentical() {
        return numberPixelsIdentical_;
      }

      public static final int NUMBER_PIXELS_DIFFERENT_FIELD_NUMBER = 2;
      private int numberPixelsDifferent_;
      /**
       * <code>uint32 number_pixels_different = 2;</code>
       */
      public int getNumberPixelsDifferent() {
        return numberPixelsDifferent_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (numberPixelsIdentical_ != 0) {
          output.writeUInt32(1, numberPixelsIdentical_);
        }
        if (numberPixelsDifferent_ != 0) {
          output.writeUInt32(2, numberPixelsDifferent_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (numberPixelsIdentical_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, numberPixelsIdentical_);
        }
        if (numberPixelsDifferent_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, numberPixelsDifferent_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics)) {
          return super.equals(obj);
        }
        androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics other = (androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics) obj;

        if (getNumberPixelsIdentical()
            != other.getNumberPixelsIdentical()) return false;
        if (getNumberPixelsDifferent()
            != other.getNumberPixelsDifferent()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NUMBER_PIXELS_IDENTICAL_FIELD_NUMBER;
        hash = (53 * hash) + getNumberPixelsIdentical();
        hash = (37 * hash) + NUMBER_PIXELS_DIFFERENT_FIELD_NUMBER;
        hash = (53 * hash) + getNumberPixelsDifferent();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code test.screenshots.ScreenshotResult.ComparisonStatistics}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:test.screenshots.ScreenshotResult.ComparisonStatistics)
          androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatisticsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return androidx.test.screenshots.ScreenshotResultProtos.internal_static_test_screenshots_ScreenshotResult_ComparisonStatistics_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return androidx.test.screenshots.ScreenshotResultProtos.internal_static_test_screenshots_ScreenshotResult_ComparisonStatistics_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.class, androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.Builder.class);
        }

        // Construct using androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          numberPixelsIdentical_ = 0;

          numberPixelsDifferent_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return androidx.test.screenshots.ScreenshotResultProtos.internal_static_test_screenshots_ScreenshotResult_ComparisonStatistics_descriptor;
        }

        @java.lang.Override
        public androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics getDefaultInstanceForType() {
          return androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.getDefaultInstance();
        }

        @java.lang.Override
        public androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics build() {
          androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics buildPartial() {
          androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics result = new androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics(this);
          result.numberPixelsIdentical_ = numberPixelsIdentical_;
          result.numberPixelsDifferent_ = numberPixelsDifferent_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics) {
            return mergeFrom((androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics other) {
          if (other == androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.getDefaultInstance()) return this;
          if (other.getNumberPixelsIdentical() != 0) {
            setNumberPixelsIdentical(other.getNumberPixelsIdentical());
          }
          if (other.getNumberPixelsDifferent() != 0) {
            setNumberPixelsDifferent(other.getNumberPixelsDifferent());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int numberPixelsIdentical_ ;
        /**
         * <code>uint32 number_pixels_identical = 1;</code>
         */
        public int getNumberPixelsIdentical() {
          return numberPixelsIdentical_;
        }
        /**
         * <code>uint32 number_pixels_identical = 1;</code>
         */
        public Builder setNumberPixelsIdentical(int value) {
          
          numberPixelsIdentical_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 number_pixels_identical = 1;</code>
         */
        public Builder clearNumberPixelsIdentical() {
          
          numberPixelsIdentical_ = 0;
          onChanged();
          return this;
        }

        private int numberPixelsDifferent_ ;
        /**
         * <code>uint32 number_pixels_different = 2;</code>
         */
        public int getNumberPixelsDifferent() {
          return numberPixelsDifferent_;
        }
        /**
         * <code>uint32 number_pixels_different = 2;</code>
         */
        public Builder setNumberPixelsDifferent(int value) {
          
          numberPixelsDifferent_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 number_pixels_different = 2;</code>
         */
        public Builder clearNumberPixelsDifferent() {
          
          numberPixelsDifferent_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:test.screenshots.ScreenshotResult.ComparisonStatistics)
      }

      // @@protoc_insertion_point(class_scope:test.screenshots.ScreenshotResult.ComparisonStatistics)
      private static final androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics();
      }

      public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ComparisonStatistics>
          PARSER = new com.google.protobuf.AbstractParser<ComparisonStatistics>() {
        @java.lang.Override
        public ComparisonStatistics parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ComparisonStatistics(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ComparisonStatistics> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ComparisonStatistics> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>.test.screenshots.ScreenshotResult.Status result = 1;</code>
     */
    public int getResultValue() {
      return result_;
    }
    /**
     * <code>.test.screenshots.ScreenshotResult.Status result = 1;</code>
     */
    public androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.Status getResult() {
      @SuppressWarnings("deprecation")
      androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.Status result = androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.Status.valueOf(result_);
      return result == null ? androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.Status.UNRECOGNIZED : result;
    }

    public static final int IMAGE_LOCATION_TEST_FIELD_NUMBER = 2;
    private volatile java.lang.Object imageLocationTest_;
    /**
     * <code>string image_location_test = 2;</code>
     */
    public java.lang.String getImageLocationTest() {
      java.lang.Object ref = imageLocationTest_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageLocationTest_ = s;
        return s;
      }
    }
    /**
     * <code>string image_location_test = 2;</code>
     */
    public com.google.protobuf.ByteString
        getImageLocationTestBytes() {
      java.lang.Object ref = imageLocationTest_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageLocationTest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGE_LOCATION_GOLDEN_FIELD_NUMBER = 3;
    private volatile java.lang.Object imageLocationGolden_;
    /**
     * <pre>
     *actual location if image exists, expected location if missing
     * </pre>
     *
     * <code>string image_location_golden = 3;</code>
     */
    public java.lang.String getImageLocationGolden() {
      java.lang.Object ref = imageLocationGolden_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageLocationGolden_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *actual location if image exists, expected location if missing
     * </pre>
     *
     * <code>string image_location_golden = 3;</code>
     */
    public com.google.protobuf.ByteString
        getImageLocationGoldenBytes() {
      java.lang.Object ref = imageLocationGolden_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageLocationGolden_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGE_LOCATION_DIFF_FIELD_NUMBER = 4;
    private volatile java.lang.Object imageLocationDiff_;
    /**
     * <code>string image_location_diff = 4;</code>
     */
    public java.lang.String getImageLocationDiff() {
      java.lang.Object ref = imageLocationDiff_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageLocationDiff_ = s;
        return s;
      }
    }
    /**
     * <code>string image_location_diff = 4;</code>
     */
    public com.google.protobuf.ByteString
        getImageLocationDiffBytes() {
      java.lang.Object ref = imageLocationDiff_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageLocationDiff_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPARISON_STATISTICS_FIELD_NUMBER = 5;
    private androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics comparisonStatistics_;
    /**
     * <code>.test.screenshots.ScreenshotResult.ComparisonStatistics comparison_statistics = 5;</code>
     */
    public boolean hasComparisonStatistics() {
      return comparisonStatistics_ != null;
    }
    /**
     * <code>.test.screenshots.ScreenshotResult.ComparisonStatistics comparison_statistics = 5;</code>
     */
    public androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics getComparisonStatistics() {
      return comparisonStatistics_ == null ? androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.getDefaultInstance() : comparisonStatistics_;
    }
    /**
     * <code>.test.screenshots.ScreenshotResult.ComparisonStatistics comparison_statistics = 5;</code>
     */
    public androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatisticsOrBuilder getComparisonStatisticsOrBuilder() {
      return getComparisonStatistics();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.Status.UNSPECIFIED.getNumber()) {
        output.writeEnum(1, result_);
      }
      if (!getImageLocationTestBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, imageLocationTest_);
      }
      if (!getImageLocationGoldenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, imageLocationGolden_);
      }
      if (!getImageLocationDiffBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, imageLocationDiff_);
      }
      if (comparisonStatistics_ != null) {
        output.writeMessage(5, getComparisonStatistics());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.Status.UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_);
      }
      if (!getImageLocationTestBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, imageLocationTest_);
      }
      if (!getImageLocationGoldenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, imageLocationGolden_);
      }
      if (!getImageLocationDiffBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, imageLocationDiff_);
      }
      if (comparisonStatistics_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getComparisonStatistics());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult)) {
        return super.equals(obj);
      }
      androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult other = (androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult) obj;

      if (result_ != other.result_) return false;
      if (!getImageLocationTest()
          .equals(other.getImageLocationTest())) return false;
      if (!getImageLocationGolden()
          .equals(other.getImageLocationGolden())) return false;
      if (!getImageLocationDiff()
          .equals(other.getImageLocationDiff())) return false;
      if (hasComparisonStatistics() != other.hasComparisonStatistics()) return false;
      if (hasComparisonStatistics()) {
        if (!getComparisonStatistics()
            .equals(other.getComparisonStatistics())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + result_;
      hash = (37 * hash) + IMAGE_LOCATION_TEST_FIELD_NUMBER;
      hash = (53 * hash) + getImageLocationTest().hashCode();
      hash = (37 * hash) + IMAGE_LOCATION_GOLDEN_FIELD_NUMBER;
      hash = (53 * hash) + getImageLocationGolden().hashCode();
      hash = (37 * hash) + IMAGE_LOCATION_DIFF_FIELD_NUMBER;
      hash = (53 * hash) + getImageLocationDiff().hashCode();
      if (hasComparisonStatistics()) {
        hash = (37 * hash) + COMPARISON_STATISTICS_FIELD_NUMBER;
        hash = (53 * hash) + getComparisonStatistics().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.screenshots.ScreenshotResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.screenshots.ScreenshotResult)
        androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return androidx.test.screenshots.ScreenshotResultProtos.internal_static_test_screenshots_ScreenshotResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return androidx.test.screenshots.ScreenshotResultProtos.internal_static_test_screenshots_ScreenshotResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.class, androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.Builder.class);
      }

      // Construct using androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        imageLocationTest_ = "";

        imageLocationGolden_ = "";

        imageLocationDiff_ = "";

        if (comparisonStatisticsBuilder_ == null) {
          comparisonStatistics_ = null;
        } else {
          comparisonStatistics_ = null;
          comparisonStatisticsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return androidx.test.screenshots.ScreenshotResultProtos.internal_static_test_screenshots_ScreenshotResult_descriptor;
      }

      @java.lang.Override
      public androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult getDefaultInstanceForType() {
        return androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.getDefaultInstance();
      }

      @java.lang.Override
      public androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult build() {
        androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult buildPartial() {
        androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult result = new androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult(this);
        result.result_ = result_;
        result.imageLocationTest_ = imageLocationTest_;
        result.imageLocationGolden_ = imageLocationGolden_;
        result.imageLocationDiff_ = imageLocationDiff_;
        if (comparisonStatisticsBuilder_ == null) {
          result.comparisonStatistics_ = comparisonStatistics_;
        } else {
          result.comparisonStatistics_ = comparisonStatisticsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult) {
          return mergeFrom((androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult other) {
        if (other == androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.getDefaultInstance()) return this;
        if (other.result_ != 0) {
          setResultValue(other.getResultValue());
        }
        if (!other.getImageLocationTest().isEmpty()) {
          imageLocationTest_ = other.imageLocationTest_;
          onChanged();
        }
        if (!other.getImageLocationGolden().isEmpty()) {
          imageLocationGolden_ = other.imageLocationGolden_;
          onChanged();
        }
        if (!other.getImageLocationDiff().isEmpty()) {
          imageLocationDiff_ = other.imageLocationDiff_;
          onChanged();
        }
        if (other.hasComparisonStatistics()) {
          mergeComparisonStatistics(other.getComparisonStatistics());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ = 0;
      /**
       * <code>.test.screenshots.ScreenshotResult.Status result = 1;</code>
       */
      public int getResultValue() {
        return result_;
      }
      /**
       * <code>.test.screenshots.ScreenshotResult.Status result = 1;</code>
       */
      public Builder setResultValue(int value) {
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.test.screenshots.ScreenshotResult.Status result = 1;</code>
       */
      public androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.Status getResult() {
        @SuppressWarnings("deprecation")
        androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.Status result = androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.Status.valueOf(result_);
        return result == null ? androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.test.screenshots.ScreenshotResult.Status result = 1;</code>
       */
      public Builder setResult(androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.test.screenshots.ScreenshotResult.Status result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object imageLocationTest_ = "";
      /**
       * <code>string image_location_test = 2;</code>
       */
      public java.lang.String getImageLocationTest() {
        java.lang.Object ref = imageLocationTest_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imageLocationTest_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string image_location_test = 2;</code>
       */
      public com.google.protobuf.ByteString
          getImageLocationTestBytes() {
        java.lang.Object ref = imageLocationTest_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageLocationTest_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string image_location_test = 2;</code>
       */
      public Builder setImageLocationTest(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageLocationTest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string image_location_test = 2;</code>
       */
      public Builder clearImageLocationTest() {
        
        imageLocationTest_ = getDefaultInstance().getImageLocationTest();
        onChanged();
        return this;
      }
      /**
       * <code>string image_location_test = 2;</code>
       */
      public Builder setImageLocationTestBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageLocationTest_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object imageLocationGolden_ = "";
      /**
       * <pre>
       *actual location if image exists, expected location if missing
       * </pre>
       *
       * <code>string image_location_golden = 3;</code>
       */
      public java.lang.String getImageLocationGolden() {
        java.lang.Object ref = imageLocationGolden_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imageLocationGolden_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *actual location if image exists, expected location if missing
       * </pre>
       *
       * <code>string image_location_golden = 3;</code>
       */
      public com.google.protobuf.ByteString
          getImageLocationGoldenBytes() {
        java.lang.Object ref = imageLocationGolden_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageLocationGolden_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *actual location if image exists, expected location if missing
       * </pre>
       *
       * <code>string image_location_golden = 3;</code>
       */
      public Builder setImageLocationGolden(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageLocationGolden_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *actual location if image exists, expected location if missing
       * </pre>
       *
       * <code>string image_location_golden = 3;</code>
       */
      public Builder clearImageLocationGolden() {
        
        imageLocationGolden_ = getDefaultInstance().getImageLocationGolden();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *actual location if image exists, expected location if missing
       * </pre>
       *
       * <code>string image_location_golden = 3;</code>
       */
      public Builder setImageLocationGoldenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageLocationGolden_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object imageLocationDiff_ = "";
      /**
       * <code>string image_location_diff = 4;</code>
       */
      public java.lang.String getImageLocationDiff() {
        java.lang.Object ref = imageLocationDiff_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imageLocationDiff_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string image_location_diff = 4;</code>
       */
      public com.google.protobuf.ByteString
          getImageLocationDiffBytes() {
        java.lang.Object ref = imageLocationDiff_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageLocationDiff_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string image_location_diff = 4;</code>
       */
      public Builder setImageLocationDiff(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageLocationDiff_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string image_location_diff = 4;</code>
       */
      public Builder clearImageLocationDiff() {
        
        imageLocationDiff_ = getDefaultInstance().getImageLocationDiff();
        onChanged();
        return this;
      }
      /**
       * <code>string image_location_diff = 4;</code>
       */
      public Builder setImageLocationDiffBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageLocationDiff_ = value;
        onChanged();
        return this;
      }

      private androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics comparisonStatistics_;
      private com.google.protobuf.SingleFieldBuilderV3<
          androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics, androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.Builder, androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatisticsOrBuilder> comparisonStatisticsBuilder_;
      /**
       * <code>.test.screenshots.ScreenshotResult.ComparisonStatistics comparison_statistics = 5;</code>
       */
      public boolean hasComparisonStatistics() {
        return comparisonStatisticsBuilder_ != null || comparisonStatistics_ != null;
      }
      /**
       * <code>.test.screenshots.ScreenshotResult.ComparisonStatistics comparison_statistics = 5;</code>
       */
      public androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics getComparisonStatistics() {
        if (comparisonStatisticsBuilder_ == null) {
          return comparisonStatistics_ == null ? androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.getDefaultInstance() : comparisonStatistics_;
        } else {
          return comparisonStatisticsBuilder_.getMessage();
        }
      }
      /**
       * <code>.test.screenshots.ScreenshotResult.ComparisonStatistics comparison_statistics = 5;</code>
       */
      public Builder setComparisonStatistics(androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics value) {
        if (comparisonStatisticsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          comparisonStatistics_ = value;
          onChanged();
        } else {
          comparisonStatisticsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.test.screenshots.ScreenshotResult.ComparisonStatistics comparison_statistics = 5;</code>
       */
      public Builder setComparisonStatistics(
          androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.Builder builderForValue) {
        if (comparisonStatisticsBuilder_ == null) {
          comparisonStatistics_ = builderForValue.build();
          onChanged();
        } else {
          comparisonStatisticsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.test.screenshots.ScreenshotResult.ComparisonStatistics comparison_statistics = 5;</code>
       */
      public Builder mergeComparisonStatistics(androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics value) {
        if (comparisonStatisticsBuilder_ == null) {
          if (comparisonStatistics_ != null) {
            comparisonStatistics_ =
              androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.newBuilder(comparisonStatistics_).mergeFrom(value).buildPartial();
          } else {
            comparisonStatistics_ = value;
          }
          onChanged();
        } else {
          comparisonStatisticsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.test.screenshots.ScreenshotResult.ComparisonStatistics comparison_statistics = 5;</code>
       */
      public Builder clearComparisonStatistics() {
        if (comparisonStatisticsBuilder_ == null) {
          comparisonStatistics_ = null;
          onChanged();
        } else {
          comparisonStatistics_ = null;
          comparisonStatisticsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.test.screenshots.ScreenshotResult.ComparisonStatistics comparison_statistics = 5;</code>
       */
      public androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.Builder getComparisonStatisticsBuilder() {
        
        onChanged();
        return getComparisonStatisticsFieldBuilder().getBuilder();
      }
      /**
       * <code>.test.screenshots.ScreenshotResult.ComparisonStatistics comparison_statistics = 5;</code>
       */
      public androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatisticsOrBuilder getComparisonStatisticsOrBuilder() {
        if (comparisonStatisticsBuilder_ != null) {
          return comparisonStatisticsBuilder_.getMessageOrBuilder();
        } else {
          return comparisonStatistics_ == null ?
              androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.getDefaultInstance() : comparisonStatistics_;
        }
      }
      /**
       * <code>.test.screenshots.ScreenshotResult.ComparisonStatistics comparison_statistics = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics, androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.Builder, androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatisticsOrBuilder> 
          getComparisonStatisticsFieldBuilder() {
        if (comparisonStatisticsBuilder_ == null) {
          comparisonStatisticsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics, androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatistics.Builder, androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult.ComparisonStatisticsOrBuilder>(
                  getComparisonStatistics(),
                  getParentForChildren(),
                  isClean());
          comparisonStatistics_ = null;
        }
        return comparisonStatisticsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.screenshots.ScreenshotResult)
    }

    // @@protoc_insertion_point(class_scope:test.screenshots.ScreenshotResult)
    private static final androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult();
    }

    public static androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ScreenshotResult>
        PARSER = new com.google.protobuf.AbstractParser<ScreenshotResult>() {
      @java.lang.Override
      public ScreenshotResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ScreenshotResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ScreenshotResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScreenshotResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public androidx.test.screenshots.ScreenshotResultProtos.ScreenshotResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_screenshots_ScreenshotResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_screenshots_ScreenshotResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_screenshots_ScreenshotResult_ComparisonStatistics_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_screenshots_ScreenshotResult_ComparisonStatistics_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027screenshot_result.proto\022\020test.screensh" +
      "ots\"\237\003\n\020ScreenshotResult\0229\n\006result\030\001 \001(\016" +
      "2).test.screenshots.ScreenshotResult.Sta" +
      "tus\022\033\n\023image_location_test\030\002 \001(\t\022\035\n\025imag" +
      "e_location_golden\030\003 \001(\t\022\033\n\023image_locatio" +
      "n_diff\030\004 \001(\t\022V\n\025comparison_statistics\030\005 " +
      "\001(\01327.test.screenshots.ScreenshotResult." +
      "ComparisonStatistics\032X\n\024ComparisonStatis" +
      "tics\022\037\n\027number_pixels_identical\030\001 \001(\r\022\037\n" +
      "\027number_pixels_different\030\002 \001(\r\"E\n\006Status" +
      "\022\017\n\013UNSPECIFIED\020\000\022\n\n\006PASSED\020\001\022\n\n\006FAILED\020" +
      "\002\022\022\n\016MISSING_GOLDEN\020\003B3\n\031androidx.test.s" +
      "creenshotsB\026ScreenshotResultProtosb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_test_screenshots_ScreenshotResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_screenshots_ScreenshotResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_screenshots_ScreenshotResult_descriptor,
        new java.lang.String[] { "Result", "ImageLocationTest", "ImageLocationGolden", "ImageLocationDiff", "ComparisonStatistics", });
    internal_static_test_screenshots_ScreenshotResult_ComparisonStatistics_descriptor =
      internal_static_test_screenshots_ScreenshotResult_descriptor.getNestedTypes().get(0);
    internal_static_test_screenshots_ScreenshotResult_ComparisonStatistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_screenshots_ScreenshotResult_ComparisonStatistics_descriptor,
        new java.lang.String[] { "NumberPixelsIdentical", "NumberPixelsDifferent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
